import { SEVERITY_ORDER } from '../engine/checks/index.js';

const BADGE = { critical: '🟥 CRITICAL', high: '🟧 HIGH', medium: '🟨 MEDIUM', low: '🟦 LOW', info: '⬜ INFO' };

export function renderMarkdown(scan) {
  const s = scan.score;
  const ins = scan.insights;
  const lines = [];
  lines.push(`# Monarch Security Audit — ${host(scan.target)}`, '');
  lines.push(`| | |`, `|---|---|`, `| **Target** | ${scan.target} |`, `| **Scan ID** | \`${scan.id}\` |`, `| **Date** | ${scan.finishedAt} |`, `| **Engine** | ${scan.crawl.engine} |`, `| **Pages crawled** | ${scan.crawl.pages.length} |`, `| **Requests observed** | ${scan.networkSummary.requests} (${fmtBytes(scan.networkSummary.bytes)}) |`, `| **Security score** | **${s.score}/100 — Grade ${s.grade}** |`, `| **Risk level** | ${ins?.riskLevel ? ins.riskLevel.toUpperCase() : 'n/a'} |`, '');
  lines.push('## Findings by severity', '', '| Severity | Count |', '|---|---|');
  for (const sev of SEVERITY_ORDER) lines.push(`| ${BADGE[sev]} | ${s.counts[sev] || 0} |`);
  lines.push('');

  if (ins) {
    lines.push(`## Executive summary`, '', `> _Generated by ${ins.provider}${ins.model ? ` (${ins.model})` : ''}_`, '', ins.executiveSummary, '');
    if (ins.attackNarrative) lines.push('### Likely attack path', '', ins.attackNarrative, '');
    if (ins.rootCauses?.length) { lines.push('### Root causes', ''); ins.rootCauses.forEach(r => lines.push(`- ${r}`)); lines.push(''); }
    if (ins.actionPlan?.length) {
      lines.push('## Prioritised remediation plan', '');
      for (const a of ins.actionPlan) {
        lines.push(`### ${a.priority}. ${a.title}  _(effort: ${a.effort})_`, '', `**Why:** ${a.why}`, '', `**How:**`, '', '```', a.how, '```', '', `Addresses: ${(a.findingIds || []).map(i => `\`${i}\``).join(', ') || '—'}`, '');
      }
    }
    if (ins.quickWins?.length) { lines.push('### Quick wins', ''); ins.quickWins.forEach(q => lines.push(`- [ ] ${q}`)); lines.push(''); }
  }

  lines.push('## Detailed findings', '');
  for (const sev of SEVERITY_ORDER) {
    const group = scan.findings.filter(f => f.severity === sev);
    if (!group.length) continue;
    lines.push(`### ${BADGE[sev]} (${group.length})`, '');
    for (const f of group) {
      lines.push(`#### ${f.title}`, '', `- **ID:** \`${f.id}\`  ·  **Category:** ${f.category}${f.cwe ? `  ·  **CWE:** ${f.cwe}` : ''}${f.owasp ? `  ·  **OWASP:** ${f.owasp}` : ''}`);
      if (f.location) lines.push(`- **Location:** ${f.location}`);
      lines.push('', f.description, '');
      if (f.evidence) lines.push('**Evidence:**', '', '```json', JSON.stringify(f.evidence, null, 2).slice(0, 1500), '```', '');
      if (f.remediation) lines.push('**Remediation:**', '', '```', f.remediation, '```', '');
      if (f.references?.length) lines.push('**References:** ' + f.references.join(' · '), '');
    }
  }

  lines.push('## Network inventory', '', `| # | Method | Status | Type | Size | Time | URL |`, `|---|---|---|---|---|---|---|`);
  for (const e of scan.network.slice(0, 200)) lines.push(`| ${e.id} | ${e.method} | ${e.error ? '✖' : e.status} | ${e.type} | ${fmtBytes(e.size || 0)} | ${e.timing.total ?? '-'}ms | ${e.url.length > 90 ? e.url.slice(0, 87) + '…' : e.url} |`);
  if (scan.network.length > 200) lines.push('', `_… ${scan.network.length - 200} more entries in the JSON export._`);
  lines.push('', '## Cookies observed', '');
  if (scan.crawl.cookies.length) {
    lines.push('| Name | Secure | HttpOnly | SameSite | Domain | Set by |', '|---|---|---|---|---|---|');
    for (const c of scan.crawl.cookies) lines.push(`| ${c.name} | ${c.secure ? '✅' : '❌'} | ${c.httpOnly ? '✅' : '❌'} | ${c.sameSite || '❌'} | ${c.domain || '(host-only)'} | ${c.setBy} |`);
  } else lines.push('_No cookies were set during the crawl._');
  lines.push('', '---', '', `_Generated by Monarch Security Engine v${scan.version}. This report is for authorised defensive auditing only._`, '');
  return lines.join('\n');
}

export function host(u) { try { return new URL(u).host; } catch { return u; } }
export function fmtBytes(n) { if (n < 1024) return `${n} B`; if (n < 1048576) return `${(n / 1024).toFixed(1)} KB`; return `${(n / 1048576).toFixed(2)} MB`; }
